version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootpass"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  flask_api:
    build:
      context: .. #Very important it refers where the root will be for the build.
      dockerfile: docker/dockerfiles/Dockerfile
    ports:
      - 8080:8080
  
  zookeeper:
    image: debezium/zookeeper
    ports:
     - "2181:2181"
  kafka:
    image: debezium/kafka
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic_test:1:1"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongodb_data_container:
