version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootpass"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  flask_api:
    build:
      context: .. #Very important it refers where the root will be for the build.
      dockerfile: docker/dockerfiles/Dockerfile
    ports:
      - 8080:8080
  
  zookeeper:
    image: 'wurstmeister/zookeeper'
    ports:
      - '2181:2181'
  kafka:
    image: 'wurstmeister/kafka'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_HOST_NAME: 'localhost'
      KAFKA_ADVERTISED_PORT: '9092'

volumes:
  mongodb_data_container:
networks:
  stream_net:
